before_install:
  - sudo apt install ruby-dev
  - sudo sh -c "echo 'deb http://download.opensuse.org/repositories/science:/gr-framework/xUbuntu_14.04/ /' > /etc/apt/sources.list.d/science:gr-framework.list"
  - sudo apt-get update
  - sudo apt-get install gr --allow-unauthenticated
  - sudo ln -s /usr/gr /usr/local/gr
language: ruby
rvm:
  - 2.2
